#!/usr/bin/env python3
"""
train_asr_word_distill.py

Character-level Conformer Transducer training using chunk-level TextGrid
supervision produced by the word-level StreamingASR model.


---------------------------------------------------------
This script uses the same per-chunk RNNT loss strategy as
train_asr_aligned_librispeech_nobatch.py.  The key difference is the
source of the TextGrid files:

  * train_asr_aligned_librispeech_nobatch.py  →  Praat forced-alignment TextGrids
  * this script                               →  TextGrids generated by
                                                 generate_chunk_textgrids.py
                                                 (word model streaming output)

Because the word model commits words at chunk boundaries the xmax of every
word interval in the generated TextGrid equals the audio end-time of the
chunk where the word was first decoded.  The per-chunk RNNT loss therefore
directly supervises the character model to emit each word's character tokens
in the same temporal chunk as the word model — a form of chunk-level
knowledge distillation without requiring explicit soft targets.

Loss (per sample)
-----------------
For each encoder chunk c:

  logits  = joint(enc_c, dec_prefix_c)       shape [1, T_c, U_c+1, V]
  loss_c  = RNNT(logits, toks_c)             if U_c > 0
           = -sum(log P(blank | t, 0))       if U_c == 0   (blank supervision)

  loss = mean over chunks with T_c > 0

Fallback: samples whose TextGrid is missing fall back to standard
full-sequence RNNT.

Extra CLI argument
------------------
--textgrid_dir <path>   Directory containing TextGrid files that mirror the
                        LibriSpeech structure (produced by
                        generate_chunk_textgrids.py --output_dir <path>).
                        When omitted, TextGrids are looked up alongside
                        each .wav file (same behaviour as the Praat version).

Usage
-----
python train_asr_word_distill.py \\
    /home/streamalign/streamASR/hparams/chunk_streaming_librispeech.yaml \\
    [--textgrid_dir /home/datasets/LibriSpeech/chunk_textgrids_word_model]
"""

import argparse
import os
import sys
import traceback
import warnings
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

warnings.filterwarnings(
    "ignore",
    message=".*Grid size.*will likely result in GPU under-utilization.*",
)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import torch
import torch.nn.functional as F
from hyperpyyaml import load_hyperpyyaml

import speechbrain as sb
from speechbrain.utils.distributed import if_main_process, run_on_main
from speechbrain.utils.fetching import fetch
from speechbrain.utils.logger import get_logger
from models.model import CharacterTokenizer, CHAR_TO_IDX

logger = get_logger(__name__)

SAMPLE_RATE = 16_000
_SPACE_ID = CHAR_TO_IDX[" "]


# ---------------------------------------------------------------------------
# TextGrid parser  (words tier only)
# ---------------------------------------------------------------------------
@dataclass
class WordInterval:
    word: str
    start: float
    end: float


def parse_textgrid_words(path: str) -> List[WordInterval]:
    """Return non-silence intervals from the 'words' tier of a TextGrid."""
    intervals: List[WordInterval] = []
    in_words_tier = False
    in_interval = False
    cur_xmin = cur_xmax = cur_text = None

    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if 'name = "words"' in line:
                in_words_tier = True
                continue
            if in_words_tier and line.startswith("name =") and '"words"' not in line:
                break
            if not in_words_tier:
                continue
            if line.startswith("intervals ["):
                in_interval = True
                cur_xmin = cur_xmax = cur_text = None
            elif in_interval:
                if line.startswith("xmin ="):
                    cur_xmin = float(line.split("=", 1)[1].strip())
                elif line.startswith("xmax ="):
                    cur_xmax = float(line.split("=", 1)[1].strip())
                elif line.startswith("text ="):
                    raw = line.split("=", 1)[1].strip().strip('"')
                    cur_text = raw
                    if cur_xmin is not None and cur_xmax is not None and cur_text:
                        intervals.append(WordInterval(cur_text, cur_xmin, cur_xmax))
                    in_interval = False

    return intervals


# ---------------------------------------------------------------------------
# ASR Brain
# ---------------------------------------------------------------------------
class ASR(sb.Brain):
    """
    Conformer Transducer with chunk-aligned RNNT training.

    The TextGrid used for chunk assignment is produced by the word-level
    StreamingASR model (generate_chunk_textgrids.py), so each word's xmax
    already falls on a chunk boundary — the assignment to encoder chunks
    is therefore exact by construction.
    """

    def __init__(self, *args, textgrid_dir: Optional[str] = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.textgrid_dir = textgrid_dir

    # ------------------------------------------------------------------
    # TextGrid path resolution
    # ------------------------------------------------------------------
    def _get_tg_path(self, wav_path: str) -> str:
        """
        Resolve the TextGrid path for *wav_path*.

        For Emilia files (detected by prefix matching against
        hparams.emilia_data_folder), the TextGrid is looked up under
        hparams.emilia_textgrid_dir.  For LibriTTS files, the existing
        textgrid_dir / alongside-wav logic is used.
        """
        emilia_data_folder = self.hparams.get("emilia_data_folder")
        emilia_tg_dir = self.hparams.get("emilia_textgrid_dir")
        if emilia_data_folder and wav_path.startswith(emilia_data_folder):
            if emilia_tg_dir:
                rel = os.path.relpath(
                    os.path.splitext(wav_path)[0], emilia_data_folder,
                )
                return os.path.join(emilia_tg_dir, rel + ".TextGrid")
            return os.path.splitext(wav_path)[0] + ".TextGrid"
        if self.textgrid_dir:
            rel = os.path.relpath(
                os.path.splitext(wav_path)[0],
                self.hparams.data_folder,
            )
            return os.path.join(self.textgrid_dir, rel + ".TextGrid")
        return os.path.splitext(wav_path)[0] + ".TextGrid"

    # ------------------------------------------------------------------
    # Forward pass
    # ------------------------------------------------------------------
    def compute_forward(self, batch, stage):
        """
        Training:   returns (enc_out, wav_lens, dynchunktrain_config).
        Valid/Test: returns (logits_transducer, wav_lens, best_hyps).
        """
        batch = batch.to(self.device)
        wavs, wav_lens = batch.sig
        tokens_with_bos, _ = batch.tokens_bos

        if stage == sb.Stage.TRAIN:
            if hasattr(self.hparams, "wav_augment"):
                wavs, wav_lens = self.hparams.wav_augment(wavs, wav_lens)
                tokens_with_bos = self.hparams.wav_augment.replicate_labels(
                    tokens_with_bos
                )

        feats = self.hparams.compute_features(wavs)

        if stage == sb.Stage.TRAIN and hasattr(self.hparams, "fea_augment"):
            feats, _ = self.hparams.fea_augment(feats, wav_lens)
            tokens_with_bos = self.hparams.fea_augment.replicate_labels(
                tokens_with_bos
            )

        current_epoch = self.hparams.epoch_counter.current

        if hasattr(self.hparams, "streaming") and self.hparams.streaming:
            dynchunktrain_config = self.hparams.dynchunktrain_config_sampler(stage)
        else:
            dynchunktrain_config = None

        feats = self.modules.normalize(feats, wav_lens, epoch=current_epoch)
        src   = self.modules.CNN(feats)
        x     = self.modules.enc(
            src,
            wav_lens,
            pad_idx=self.hparams.pad_index,
            dynchunktrain_config=dynchunktrain_config,
        )
        x = self.modules.proj_enc(x)  # [B, T, D]

        if stage == sb.Stage.TRAIN:
            return x, wav_lens, dynchunktrain_config

        e_in  = self.modules.emb(tokens_with_bos)
        e_in  = F.dropout(e_in, self.hparams.dec_emb_dropout, training=False)
        h, _  = self.modules.dec(e_in)
        h     = F.dropout(h, self.hparams.dec_dropout, training=False)
        h     = self.modules.proj_dec(h)
        joint = self.modules.Tjoint(x.unsqueeze(2), h.unsqueeze(1))
        logits_transducer = self.modules.transducer_lin(joint)

        if stage == sb.Stage.VALID:
            best_hyps, _, _, _ = self.hparams.Greedysearcher(x)
            return logits_transducer, wav_lens, best_hyps
        else:
            best_hyps, _, _, _ = self.hparams.Beamsearcher(x)
            return logits_transducer, wav_lens, best_hyps

    # ------------------------------------------------------------------
    # Per-chunk RNNT helpers
    # ------------------------------------------------------------------
    def _run_decoder_chunk(
        self,
        enc_c: torch.Tensor,   # [1, T_c, D]
        toks: List[int],        # target tokens for this chunk (no BOS)
        prev_toks: List[int],   # all tokens from prior chunks (no BOS)
    ):
        """
        Run decoder + joint + transducer_lin on one chunk with full causal
        conditioning on all previously decoded tokens.

        The decoder receives [BOS, *prev_toks, *toks] so that its hidden
        state is conditioned on the complete causal prefix.  Only the last
        U+1 decoder outputs (corresponding to this chunk's tokens) are used
        for the joint network.

        Returns
        -------
        logits : [1, T_c, U+1, V]
        toks_t : [1, U]  int32
        """
        device = enc_c.device
        U = len(toks)
        toks_t = torch.tensor(toks, device=device, dtype=torch.int32).unsqueeze(0)

        all_tok_ids = [self.hparams.bos_index] + prev_toks + toks
        all_tok_t   = torch.tensor(all_tok_ids, device=device, dtype=torch.long).unsqueeze(0)

        e_in  = self.modules.emb(all_tok_t)
        e_in  = F.dropout(e_in, self.hparams.dec_emb_dropout, training=True)
        h_dec, _ = self.modules.dec(e_in)
        h_dec = F.dropout(h_dec, self.hparams.dec_dropout, training=True)
        h_dec = self.modules.proj_dec(h_dec)  # [1, P+U+1, D]

        P = len(prev_toks)
        h_dec = h_dec[:, P:, :]  # [1, U+1, D]

        joint  = self.modules.Tjoint(enc_c.unsqueeze(2), h_dec.unsqueeze(1))
        logits = self.modules.transducer_lin(joint)  # [1, T_c, U+1, V]

        return logits, toks_t

    def _per_chunk_rnnt_loss(
        self,
        enc_out_b: torch.Tensor,  # [T_full, D]
        wav_len_ratio: float,
        wav_path: str,
        T_full: int,
        chunk_size: int,
    ) -> Optional[torch.Tensor]:
        """
        Compute the chunk-aligned RNNT loss for one utterance.

        Reads the word-model-generated TextGrid (produced by
        generate_chunk_textgrids.py) to assign each word's character tokens
        to the correct encoder chunk.  iv.end in the TextGrid is an encoder
        frame index; the chunk is recovered as:
            ci = max(0, (round(iv.end) - 1) // chunk_size)

        Loss per chunk
        --------------
        - Non-empty chunk (U > 0): standard RNNT loss on enc_c vs toks_c
        - Empty chunk   (U = 0): negative sum of log P(blank | t, 0)
                                  across encoder frames in this chunk

        Returns None if the TextGrid is absent/unreadable (caller falls
        back to full-sequence RNNT).
        """
        tg_path = self._get_tg_path(wav_path)
        if not os.path.exists(tg_path):
            return None

        word_intervals = parse_textgrid_words(tg_path)
        if not word_intervals:
            return None

        T_actual = max(1, round(wav_len_ratio * T_full))

        # Assign each word's character tokens to the chunk covering iv.end
        chunk_to_tokens: dict = defaultdict(list)
        for iv in word_intervals:
            # iv.word is the raw per-chunk text produced by the word model
            # (▁ already replaced with space).  Spaces are embedded, so we
            # encode the whole string directly without appending extra spaces.
            chunk_toks = self.tokenizer.encode(iv.word.upper())
            if not chunk_toks:
                continue

            # iv.end is the encoder frame end-index for this chunk.
            ci = max(0, (round(iv.end) - 1) // chunk_size)
            ci = min(ci, n_chunks - 1)
            chunk_to_tokens[ci].extend(chunk_toks)

        n_chunks = (T_actual + chunk_size - 1) // chunk_size
        chunk_losses: List[torch.Tensor] = []
        prev_toks: List[int] = []

        for ci in range(n_chunks):
            toks = chunk_to_tokens[ci]

            cs  = ci * chunk_size
            ce  = min((ci + 1) * chunk_size, T_actual)
            T_c = ce - cs
            U   = len(toks)

            if T_c <= 0:
                prev_toks = prev_toks + toks
                continue

            enc_c = enc_out_b[cs:ce].unsqueeze(0)  # [1, T_c, D]

            try:
                logits, toks_t = self._run_decoder_chunk(enc_c, toks, prev_toks)
                if U == 0:
                    # Empty chunk: supervise blank emissions only
                    log_probs = logits.log_softmax(-1)          # [1, T_c, 1, V]
                    blank_lp  = log_probs[0, :, 0, self.hparams.blank_index]  # [T_c]
                    loss_c    = -blank_lp.sum()
                else:
                    ones   = torch.ones(1, device=enc_out_b.device)
                    loss_c = self.hparams.transducer_cost(
                        logits, toks_t.long(), ones, ones
                    )
                if torch.isfinite(loss_c):
                    chunk_losses.append(loss_c)
            except Exception:
                pass

            prev_toks = prev_toks + toks

        if not chunk_losses:
            return None

        return torch.stack(chunk_losses).mean()

    def _full_seq_rnnt_loss(
        self,
        enc_out_b: torch.Tensor,  # [T_full, D]
        tok_bos_b: torch.Tensor,  # [U+1]
        toks_b: torch.Tensor,     # [U]
        T_actual: int,
    ) -> Optional[torch.Tensor]:
        """Standard full-sequence RNNT loss (fallback when TextGrid is absent)."""
        enc_b = enc_out_b[:T_actual].unsqueeze(0)
        U     = toks_b.shape[0]
        if U == 0 or T_actual == 0:
            return None

        e_in  = self.modules.emb(tok_bos_b.unsqueeze(0))
        e_in  = F.dropout(e_in, self.hparams.dec_emb_dropout, training=True)
        h_dec, _ = self.modules.dec(e_in)
        h_dec = F.dropout(h_dec, self.hparams.dec_dropout, training=True)
        h_dec = self.modules.proj_dec(h_dec)

        joint  = self.modules.Tjoint(enc_b.unsqueeze(2), h_dec.unsqueeze(1))
        logits = self.modules.transducer_lin(joint)

        ones = torch.ones(1, device=enc_out_b.device)
        loss = self.hparams.transducer_cost(
            logits, toks_b.long().unsqueeze(0), ones, ones
        )
        return loss if torch.isfinite(loss) else None

    # ------------------------------------------------------------------
    # Objectives
    # ------------------------------------------------------------------
    def compute_objectives(self, predictions, batch, stage):
        """
        Training  → per-chunk RNNT (word-model TextGrid supervision).
        Valid/Test → standard full-sequence RNNT + CER.
        """
        ids = batch.id
        tokens, token_lens       = batch.tokens
        tokens_eos, token_eos_lens = batch.tokens_eos

        # ── Validation / Test ─────────────────────────────────────────
        if stage != sb.Stage.TRAIN:
            logits_transducer, wav_lens, predicted_tokens = predictions
            loss = self.hparams.transducer_cost(
                logits_transducer, tokens, wav_lens, token_lens
            )
            predicted_words = [
                self.tokenizer.decode(utt_seq).lower().split()
                for utt_seq in predicted_tokens
            ]
            target_words = [lbl.lower().split() for lbl in batch.wrd]
            self.cer_metric.append(ids, predicted_words, target_words)
            return loss

        # ── Training ──────────────────────────────────────────────────
        enc_out, wav_lens, dynchunktrain_config = predictions

        if hasattr(self.hparams, "fea_augment"):
            (
                tokens,
                token_lens,
                tokens_eos,
                token_eos_lens,
            ) = self.hparams.fea_augment.replicate_multiple_labels(
                tokens, token_lens, tokens_eos, token_eos_lens
            )

        B      = enc_out.shape[0]
        T_full = enc_out.shape[1]

        chunk_size = (
            dynchunktrain_config.chunk_size
            if dynchunktrain_config is not None
            else T_full
        )

        wav_paths = batch.wav
        tokens_with_bos, _ = batch.tokens_bos

        all_losses: List[torch.Tensor] = []

        for b in range(B):
            T_actual = max(1, round(wav_lens[b].item() * T_full))
            wav_path = wav_paths[b]
            sample_loss: Optional[torch.Tensor] = None

            # Primary: per-chunk RNNT using word-model TextGrid
            if dynchunktrain_config is not None:
                try:
                    sample_loss = self._per_chunk_rnnt_loss(
                        enc_out[b],
                        wav_lens[b].item(),
                        wav_path,
                        T_full,
                        chunk_size,
                    )
                except Exception:
                    sample_loss = None

            # Fallback: full-sequence RNNT
            if sample_loss is None:
                tok_len_b  = max(1, round(token_lens[b].item() * tokens.shape[1]))
                toks_b     = tokens[b, :tok_len_b]
                tok_bos_b  = tokens_with_bos[b, : tok_len_b + 1]
                sample_loss = self._full_seq_rnnt_loss(
                    enc_out[b], tok_bos_b, toks_b, T_actual
                )

            if sample_loss is not None:
                all_losses.append(sample_loss)

        if all_losses:
            loss = torch.stack(all_losses).mean()
        else:
            loss = enc_out.sum() * 0.0

        return loss

    # ------------------------------------------------------------------
    # Lifecycle hooks
    # ------------------------------------------------------------------
    def on_fit_batch_end(self, batch, outputs, loss, should_step):
        if should_step:
            self.hparams.noam_annealing(self.optimizer)

    def on_stage_start(self, stage, epoch):
        if stage != sb.Stage.TRAIN:
            self.cer_metric = self.hparams.cer_computer()

    def on_stage_end(self, stage, stage_loss, epoch):
        stage_stats = {"loss": stage_loss}

        if stage == sb.Stage.TRAIN:
            self.train_stats = stage_stats
        else:
            stage_stats["CER"] = self.cer_metric.summarize("error_rate")

        if stage == sb.Stage.VALID:
            lr        = self.hparams.noam_annealing.current_lr
            steps     = self.optimizer_step
            optimizer = self.optimizer.__class__.__name__

            self.hparams.train_logger.log_stats(
                stats_meta={
                    "epoch": epoch,
                    "lr": lr,
                    "steps": steps,
                    "optimizer": optimizer,
                },
                train_stats=self.train_stats,
                valid_stats=stage_stats,
            )

            self.checkpointer.save_and_keep_only(
                meta={"CER": stage_stats["CER"], "epoch": epoch},
                min_keys=["CER"],
                num_to_keep=self.hparams.avg_checkpoints,
            )

        elif stage == sb.Stage.TEST:
            self.hparams.train_logger.log_stats(
                stats_meta={"Epoch loaded": self.hparams.epoch_counter.current},
                test_stats=stage_stats,
            )

            if if_main_process():
                with open(self.hparams.test_wer_file, "w", encoding="utf-8") as w:
                    self.cer_metric.write_stats(w)

            self.checkpointer.save_and_keep_only(
                meta={"CER": -0.1, "epoch": epoch},
                min_keys=["CER"],
                num_to_keep=1,
            )

    def on_evaluate_start(self, max_key=None, min_key=None):
        super().on_evaluate_start()
        ckpts = self.checkpointer.find_checkpoints(max_key=max_key, min_key=min_key)
        ckpt  = sb.utils.checkpoints.average_checkpoints(
            ckpts, recoverable_name="model"
        )
        self.hparams.model.load_state_dict(ckpt, strict=True)
        self.hparams.model.eval()


# ---------------------------------------------------------------------------
# Pretrained weight loading (encoder + normalizer only)
# ---------------------------------------------------------------------------
def load_pretrained_encoder_only(hparams, device, load_enc=True):
    src     = hparams["pretrained_source"]
    savedir = Path(hparams["pretrained_save"])
    savedir.mkdir(parents=True, exist_ok=True)

    model_ckpt = fetch("model.ckpt",      source=src, savedir=str(savedir))
    norm_ckpt  = fetch("normalizer.ckpt", source=src, savedir=str(savedir))

    norm_state = torch.load(norm_ckpt, map_location="cpu")
    if isinstance(norm_state, dict) and "state_dict" in norm_state:
        norm_state = norm_state["state_dict"]
    hparams["normalize"].load_state_dict(norm_state, strict=False)

    ckpt = torch.load(model_ckpt, map_location="cpu")
    sd   = ckpt["model"] if isinstance(ckpt, dict) and "model" in ckpt else ckpt

    keep_prefixes = ("0.", "1.", "4.") if load_enc else ("0.", "4.")
    filtered      = {k: v for k, v in sd.items() if k.startswith(keep_prefixes)}

    missing, unexpected = hparams["model"].load_state_dict(filtered, strict=False)
    logger.info(f"[Pretrained] loaded:     {len(filtered)}")
    logger.info(f"[Pretrained] missing:    {len(missing)}")
    logger.info(f"[Pretrained] unexpected: {len(unexpected)}")

    hparams["model"].to(device)
    hparams["normalize"].to(device)


# ---------------------------------------------------------------------------
# Data preparation
# ---------------------------------------------------------------------------
def dataio_prepare(hparams, tokenizer, textgrid_dir: Optional[str] = None):
    """
    Prepare datasets from LibriSpeech CSV files.

    Training data is filtered to utterances that have a TextGrid produced by
    generate_chunk_textgrids.py (or Praat forced alignment, which has the
    same format).

    textgrid_dir : if given, TextGrid files are looked up under this directory
                  mirroring the LibriSpeech structure, rather than alongside
                  each .wav file.
    """
    data_folder = hparams["data_folder"]
    valid_data_folder = hparams.get("valid_data_folder", data_folder)
    emilia_data_folder = hparams.get("emilia_data_folder")
    emilia_tg_dir = hparams.get("emilia_textgrid_dir")

    def tg_exists(wav: str) -> bool:
        if emilia_data_folder and wav.startswith(emilia_data_folder):
            if emilia_tg_dir:
                rel = os.path.relpath(os.path.splitext(wav)[0], emilia_data_folder)
                return os.path.exists(os.path.join(emilia_tg_dir, rel + ".TextGrid"))
            return os.path.exists(os.path.splitext(wav)[0] + ".TextGrid")
        if textgrid_dir:
            rel = os.path.relpath(os.path.splitext(wav)[0], data_folder)
            return os.path.exists(os.path.join(textgrid_dir, rel + ".TextGrid"))
        return os.path.exists(os.path.splitext(wav)[0] + ".TextGrid")

    # Merge training CSV splits
    merged_train: dict = {}
    for csv in hparams["train_csv"]:
        d = sb.dataio.dataset.DynamicItemDataset.from_csv(
            csv_path=csv,
            replacements={"data_root": data_folder},
        )
        merged_train.update(d.data)

    # Merge Emilia training data if configured
    if "emilia_train_csv" in hparams:
        emilia_csvs = hparams["emilia_train_csv"]
        if not isinstance(emilia_csvs, list):
            emilia_csvs = [emilia_csvs]
        for csv in emilia_csvs:
            d = sb.dataio.dataset.DynamicItemDataset.from_csv(
                csv_path=csv,
                replacements={"data_root": emilia_data_folder},
            )
            merged_train.update(d.data)

    train_data = sb.dataio.dataset.DynamicItemDataset(merged_train)

    # Filter to utterances that have a chunk TextGrid
    n_before = len(train_data)
    train_data = train_data.filtered_sorted(
        key_test={"wav": tg_exists},
        sort_key="duration" if hparams["sorting"] != "random" else None,
        reverse=(hparams["sorting"] == "descending"),
    )
    n_after = len(train_data)
    logger.info(
        f"Chunk TextGrid filter: kept {n_after}/{n_before} training utterances "
        f"({n_before - n_after} dropped)."
    )

    if hparams["sorting"] in ("ascending", "descending"):
        hparams["train_dataloader_opts"]["shuffle"] = False

    valid_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
        csv_path=hparams["valid_csv"],
        replacements={"data_root": valid_data_folder},
    )
    valid_data = valid_data.filtered_sorted(sort_key="duration")

    test_datasets = {}
    for csv in hparams["test_csv"]:
        name = Path(csv).stem
        test_datasets[name] = sb.dataio.dataset.DynamicItemDataset.from_csv(
            csv_path=csv,
            replacements={"data_root": data_folder},
        )
        test_datasets[name] = test_datasets[name].filtered_sorted(sort_key="duration")

    datasets = [train_data, valid_data] + list(test_datasets.values())

    @sb.utils.data_pipeline.takes("wav")
    @sb.utils.data_pipeline.provides("sig")
    def audio_pipeline(wav):
        return sb.dataio.dataio.read_audio(wav)

    sb.dataio.dataset.add_dynamic_item(datasets, audio_pipeline)

    @sb.utils.data_pipeline.takes("wrd")
    @sb.utils.data_pipeline.provides(
        "wrd", "tokens_list", "tokens_bos", "tokens_eos", "tokens"
    )
    def text_pipeline(wrd):
        yield wrd
        tokens_list = tokenizer.encode(wrd.upper())
        yield tokens_list
        yield torch.LongTensor([hparams["bos_index"]] + tokens_list)
        yield torch.LongTensor(tokens_list + [hparams["eos_index"]])
        yield torch.LongTensor(tokens_list)

    sb.dataio.dataset.add_dynamic_item(datasets, text_pipeline)

    sb.dataio.dataset.set_output_keys(
        datasets,
        ["id", "sig", "wav", "wrd", "tokens_bos", "tokens_eos", "tokens"],
    )

    train_batch_sampler = None
    valid_batch_sampler = None

    if hparams["dynamic_batching"]:
        from speechbrain.dataio.sampler import DynamicBatchSampler

        dyn = hparams["dynamic_batch_sampler"]
        num_buckets = dyn["num_buckets"]

        train_batch_sampler = DynamicBatchSampler(
            train_data,
            dyn["max_batch_len"],
            num_buckets=num_buckets,
            length_func=lambda x: x["duration"],
            shuffle=dyn["shuffle_ex"],
            batch_ordering=dyn["batch_ordering"],
        )

        valid_batch_sampler = DynamicBatchSampler(
            valid_data,
            dyn["max_batch_len_val"],
            num_buckets=num_buckets,
            length_func=lambda x: x["duration"],
            shuffle=dyn["shuffle_ex"],
            batch_ordering=dyn["batch_ordering"],
        )

    return (
        train_data,
        valid_data,
        test_datasets,
        train_batch_sampler,
        valid_batch_sampler,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_extra_args():
    """
    Parse --textgrid_dir before passing the remaining argv to SpeechBrain.
    SpeechBrain's sb.parse_arguments does not know about this flag.
    """
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument(
        "--textgrid_dir", type=str, default=None,
        help=(
            "Directory containing chunk-level TextGrid files produced by "
            "generate_chunk_textgrids.py --output_dir <path>. "
            "The directory must mirror the LibriSpeech sub-directory structure. "
            "If omitted, TextGrids are looked up alongside each .wav file."
        ),
    )
    known, remaining = p.parse_known_args()
    return known, remaining


if __name__ == "__main__":
    extra_args, sb_argv = _parse_extra_args()
    sys.argv[1:] = sb_argv

    hparams_file, run_opts, overrides = sb.parse_arguments(sys.argv[1:])

    device = getattr(run_opts, "device", "cuda")
    if device == "cpu" and "use_torchaudio: True" not in overrides:
        overrides += "\nuse_torchaudio: True"

    sb.utils.distributed.ddp_init_group(run_opts)

    with open(hparams_file, encoding="utf-8") as fin:
        hparams = load_hyperpyyaml(fin, overrides)

    sb.create_experiment_directory(
        experiment_directory=hparams["output_folder"],
        hyperparams_to_save=hparams_file,
        overrides=overrides,
    )

    tokenizer = hparams["tokenizer"]
    logger.info(f"Tokenizer vocab size: {tokenizer.vocab_size}")

    if extra_args.textgrid_dir:
        logger.info(f"TextGrid directory: {extra_args.textgrid_dir}")

    (
        train_data,
        valid_data,
        test_datasets,
        train_bsampler,
        valid_bsampler,
    ) = dataio_prepare(hparams, tokenizer, textgrid_dir=extra_args.textgrid_dir)

    load_pretrained_encoder_only(hparams, device=device, load_enc=True)

    asr_brain = ASR(
        modules=hparams["modules"],
        opt_class=hparams["opt_class"],
        hparams=hparams,
        run_opts=run_opts,
        checkpointer=hparams["checkpointer"],
        textgrid_dir=extra_args.textgrid_dir,
    )
    asr_brain.tokenizer = tokenizer

    train_dataloader_opts = hparams["train_dataloader_opts"]
    valid_dataloader_opts = hparams["valid_dataloader_opts"]

    if train_bsampler is not None:
        train_dataloader_opts = {
            "batch_sampler": train_bsampler,
            "num_workers": hparams["num_workers"],
        }
    if valid_bsampler is not None:
        valid_dataloader_opts = {"batch_sampler": valid_bsampler}

    asr_brain.fit(
        asr_brain.hparams.epoch_counter,
        train_data,
        valid_data,
        train_loader_kwargs=train_dataloader_opts,
        valid_loader_kwargs=valid_dataloader_opts,
    )

    os.makedirs(hparams["output_wer_folder"], exist_ok=True)
    for k in test_datasets.keys():
        asr_brain.hparams.test_wer_file = os.path.join(
            hparams["output_wer_folder"], f"wer_{k}.txt"
        )
        asr_brain.evaluate(
            test_datasets[k],
            test_loader_kwargs=hparams["test_dataloader_opts"],
            min_key="CER",
        )
